// ─── Business Blueprint — Static Sector Config ───────────────────────────────

export type SectorSlug = 'ecommerce' | 'saas' | 'agence' | 'consultant' | 'createur' | 'b2b'

export interface BlueprintTask {
  id: string
  label: string
  category: string        // maps to agents.category
  task_category: string   // grouping label shown in UI
  roi_estimate: string    // e.g. "3h/semaine"
  roi_detail: string      // breakdown shown on hover
  use_cases: string[]     // tags to match agents.use_cases
}

export interface SectorConfig {
  slug: SectorSlug
  label: string
  description: string
  icon: string
  tasks: BlueprintTask[]
}

export const SECTORS: Record<SectorSlug, SectorConfig> = {
  ecommerce: {
    slug: 'ecommerce',
    label: 'E-commerce',
    description: 'Boutique en ligne, dropshipping, marketplace — automatise tes ventes et ta relation client.',
    icon: '',
    tasks: [
      {
        id: 'ecommerce-service-client',
        label: 'Service client',
        category: 'customer_service',
        task_category: 'Opérations',
        roi_estimate: '3h/semaine',
        roi_detail: '2h/semaine sur les réponses email + 1h sur les retours produits',
        use_cases: ['chatbot', 'support', 'customer_service'],
      },
      {
        id: 'ecommerce-email-marketing',
        label: 'Email marketing',
        category: 'copywriting',
        task_category: 'Marketing',
        roi_estimate: '4h/semaine',
        roi_detail: '3h/semaine sur la rédaction de campagnes + 1h sur la segmentation',
        use_cases: ['email', 'copywriting', 'newsletter'],
      },
      {
        id: 'ecommerce-visuels-produits',
        label: 'Création visuels produits',
        category: 'image',
        task_category: 'Contenu',
        roi_estimate: '5h/semaine',
        roi_detail: '4h/semaine sur la création de visuels + 1h sur les retouches',
        use_cases: ['image', 'design', 'product'],
      },
      {
        id: 'ecommerce-publicites',
        label: 'Création publicités',
        category: 'image',
        task_category: 'Marketing',
        roi_estimate: '6h/semaine',
        roi_detail: '4h/semaine sur les créas publicitaires + 2h sur les variantes',
        use_cases: ['ads', 'image', 'design', 'social'],
      },
      {
        id: 'ecommerce-recherche-produits',
        label: 'Recherche produits gagnants',
        category: 'research',
        task_category: 'Analyse',
        roi_estimate: '4h/semaine',
        roi_detail: '3h/semaine sur la veille produits + 1h sur l\'analyse tendances',
        use_cases: ['research', 'market', 'product'],
      },
      {
        id: 'ecommerce-seo',
        label: 'SEO fiches produits',
        category: 'seo',
        task_category: 'Contenu',
        roi_estimate: '3h/semaine',
        roi_detail: '2h/semaine sur l\'optimisation des fiches + 1h sur les mots-clés',
        use_cases: ['seo', 'content', 'product'],
      },
      {
        id: 'ecommerce-reseaux-sociaux',
        label: 'Gestion réseaux sociaux',
        category: 'social',
        task_category: 'Marketing',
        roi_estimate: '5h/semaine',
        roi_detail: '3h/semaine sur la création de posts + 2h sur la planification',
        use_cases: ['social', 'content', 'scheduling'],
      },
      {
        id: 'ecommerce-analyse-concurrents',
        label: 'Analyse concurrents',
        category: 'analytics',
        task_category: 'Analyse',
        roi_estimate: '2h/semaine',
        roi_detail: '1.5h/semaine sur la veille concurrentielle + 0.5h sur les rapports',
        use_cases: ['analytics', 'research', 'competitive'],
      },
      {
        id: 'ecommerce-automatisation-commandes',
        label: 'Automatisation commandes',
        category: 'automation',
        task_category: 'Opérations',
        roi_estimate: '4h/semaine',
        roi_detail: '3h/semaine sur le traitement des commandes + 1h sur les notifications',
        use_cases: ['automation', 'workflow', 'ecommerce'],
      },
    ],
  },

  saas: {
    slug: 'saas',
    label: 'SaaS',
    description: 'Logiciel en ligne, app web — accélère ta croissance et réduis ton churn.',
    icon: '',
    tasks: [
      {
        id: 'saas-copywriting-landing',
        label: 'Copywriting landing page',
        category: 'copywriting',
        task_category: 'Growth',
        roi_estimate: '5h/semaine',
        roi_detail: '3h/semaine sur la rédaction + 2h sur les tests A/B',
        use_cases: ['copywriting', 'landing', 'conversion'],
      },
      {
        id: 'saas-prospection-b2b',
        label: 'Prospection B2B',
        category: 'prospecting',
        task_category: 'Growth',
        roi_estimate: '6h/semaine',
        roi_detail: '4h/semaine sur la recherche de leads + 2h sur la personnalisation',
        use_cases: ['prospecting', 'b2b', 'outreach'],
      },
      {
        id: 'saas-support-utilisateur',
        label: 'Support utilisateur',
        category: 'customer_service',
        task_category: 'Support',
        roi_estimate: '4h/semaine',
        roi_detail: '3h/semaine sur les tickets + 1h sur la base de connaissances',
        use_cases: ['support', 'chatbot', 'customer_service'],
      },
      {
        id: 'saas-documentation',
        label: 'Documentation produit',
        category: 'copywriting',
        task_category: 'Produit',
        roi_estimate: '3h/semaine',
        roi_detail: '2h/semaine sur la rédaction + 1h sur la mise à jour',
        use_cases: ['documentation', 'copywriting', 'technical'],
      },
      {
        id: 'saas-analyse-comportement',
        label: 'Analyse comportement utilisateurs',
        category: 'analytics',
        task_category: 'Produit',
        roi_estimate: '3h/semaine',
        roi_detail: '2h/semaine sur l\'analyse des données + 1h sur les rapports',
        use_cases: ['analytics', 'user', 'product'],
      },
      {
        id: 'saas-contenu-blog',
        label: 'Création contenu blog',
        category: 'copywriting',
        task_category: 'Growth',
        roi_estimate: '4h/semaine',
        roi_detail: '3h/semaine sur la rédaction + 1h sur l\'optimisation SEO',
        use_cases: ['blog', 'copywriting', 'seo', 'content'],
      },
      {
        id: 'saas-onboarding',
        label: 'Automatisation onboarding',
        category: 'automation',
        task_category: 'Support',
        roi_estimate: '5h/semaine',
        roi_detail: '3h/semaine sur les séquences email + 2h sur les tutoriels',
        use_cases: ['automation', 'onboarding', 'email'],
      },
    ],
  },

  agence: {
    slug: 'agence',
    label: 'Agence',
    description: 'Agence marketing, créative ou digitale — livre plus vite et prospecte mieux.',
    icon: '',
    tasks: [
      {
        id: 'agence-prospection-clients',
        label: 'Prospection clients',
        category: 'prospecting',
        task_category: 'Acquisition',
        roi_estimate: '6h/semaine',
        roi_detail: '4h/semaine sur la recherche de prospects + 2h sur les relances',
        use_cases: ['prospecting', 'outreach', 'b2b'],
      },
      {
        id: 'agence-creation-contenu',
        label: 'Création contenu clients',
        category: 'copywriting',
        task_category: 'Livraison',
        roi_estimate: '8h/semaine',
        roi_detail: '5h/semaine sur la rédaction + 3h sur les révisions',
        use_cases: ['copywriting', 'content', 'social'],
      },
      {
        id: 'agence-reporting',
        label: 'Reporting clients',
        category: 'analytics',
        task_category: 'Admin',
        roi_estimate: '4h/semaine',
        roi_detail: '3h/semaine sur la collecte de données + 1h sur la mise en forme',
        use_cases: ['analytics', 'reporting', 'dashboard'],
      },
      {
        id: 'agence-visuels',
        label: 'Création visuels',
        category: 'image',
        task_category: 'Livraison',
        roi_estimate: '5h/semaine',
        roi_detail: '4h/semaine sur la création + 1h sur les retouches',
        use_cases: ['image', 'design', 'creative'],
      },
      {
        id: 'agence-veille',
        label: 'Veille sectorielle',
        category: 'research',
        task_category: 'Acquisition',
        roi_estimate: '3h/semaine',
        roi_detail: '2h/semaine sur la veille + 1h sur la synthèse',
        use_cases: ['research', 'market', 'competitive'],
      },
      {
        id: 'agence-automatisation-workflows',
        label: 'Automatisation workflows',
        category: 'automation',
        task_category: 'Admin',
        roi_estimate: '5h/semaine',
        roi_detail: '3h/semaine sur la configuration + 2h sur la maintenance',
        use_cases: ['automation', 'workflow', 'productivity'],
      },
    ],
  },

  consultant: {
    slug: 'consultant',
    label: 'Consultant',
    description: 'Consultant indépendant ou freelance — gagne du temps sur les tâches répétitives.',
    icon: '',
    tasks: [
      {
        id: 'consultant-prospection-linkedin',
        label: 'Prospection LinkedIn',
        category: 'prospecting',
        task_category: 'Acquisition',
        roi_estimate: '5h/semaine',
        roi_detail: '3h/semaine sur la recherche + 2h sur les messages personnalisés',
        use_cases: ['prospecting', 'linkedin', 'outreach'],
      },
      {
        id: 'consultant-propositions',
        label: 'Rédaction propositions',
        category: 'copywriting',
        task_category: 'Livraison',
        roi_estimate: '4h/semaine',
        roi_detail: '3h/semaine sur la rédaction + 1h sur la personnalisation',
        use_cases: ['copywriting', 'proposal', 'business'],
      },
      {
        id: 'consultant-recherche-sectorielle',
        label: 'Recherche sectorielle',
        category: 'research',
        task_category: 'Livraison',
        roi_estimate: '3h/semaine',
        roi_detail: '2h/semaine sur la recherche + 1h sur la synthèse',
        use_cases: ['research', 'market', 'analysis'],
      },
      {
        id: 'consultant-presentations',
        label: 'Création présentations',
        category: 'copywriting',
        task_category: 'Livraison',
        roi_estimate: '3h/semaine',
        roi_detail: '2h/semaine sur la structure + 1h sur le contenu',
        use_cases: ['presentation', 'copywriting', 'design'],
      },
      {
        id: 'consultant-veille-concurrentielle',
        label: 'Veille concurrentielle',
        category: 'research',
        task_category: 'Acquisition',
        roi_estimate: '2h/semaine',
        roi_detail: '1.5h/semaine sur la veille + 0.5h sur les alertes',
        use_cases: ['research', 'competitive', 'market'],
      },
      {
        id: 'consultant-facturation',
        label: 'Automatisation facturation',
        category: 'automation',
        task_category: 'Admin',
        roi_estimate: '2h/semaine',
        roi_detail: '1.5h/semaine sur la génération de factures + 0.5h sur les relances',
        use_cases: ['automation', 'billing', 'admin'],
      },
    ],
  },

  createur: {
    slug: 'createur',
    label: 'Créateur',
    description: 'YouTubeur, streamer, créateur de contenu — produis plus et engage ta communauté.',
    icon: '',
    tasks: [
      {
        id: 'createur-script-video',
        label: 'Script et idées vidéo',
        category: 'copywriting',
        task_category: 'Contenu',
        roi_estimate: '5h/semaine',
        roi_detail: '3h/semaine sur les scripts + 2h sur la recherche d\'idées',
        use_cases: ['copywriting', 'video', 'script', 'content'],
      },
      {
        id: 'createur-miniatures',
        label: 'Création miniatures',
        category: 'image',
        task_category: 'Contenu',
        roi_estimate: '3h/semaine',
        roi_detail: '2h/semaine sur la création + 1h sur les tests',
        use_cases: ['image', 'design', 'thumbnail', 'youtube'],
      },
      {
        id: 'createur-sous-titres',
        label: 'Sous-titres et transcription',
        category: 'copywriting',
        task_category: 'Contenu',
        roi_estimate: '4h/semaine',
        roi_detail: '3h/semaine sur la transcription + 1h sur la correction',
        use_cases: ['transcription', 'subtitles', 'video', 'copywriting'],
      },
      {
        id: 'createur-newsletter',
        label: 'Email newsletter',
        category: 'copywriting',
        task_category: 'Monétisation',
        roi_estimate: '3h/semaine',
        roi_detail: '2h/semaine sur la rédaction + 1h sur la mise en forme',
        use_cases: ['email', 'newsletter', 'copywriting'],
      },
      {
        id: 'createur-montage',
        label: 'Montage vidéo assisté',
        category: 'video',
        task_category: 'Contenu',
        roi_estimate: '6h/semaine',
        roi_detail: '5h/semaine sur le montage + 1h sur les effets',
        use_cases: ['video', 'editing', 'content'],
      },
      {
        id: 'createur-analyse-stats',
        label: 'Analyse statistiques',
        category: 'analytics',
        task_category: 'Monétisation',
        roi_estimate: '2h/semaine',
        roi_detail: '1.5h/semaine sur l\'analyse + 0.5h sur les rapports',
        use_cases: ['analytics', 'youtube', 'social', 'data'],
      },
      {
        id: 'createur-communaute',
        label: 'Gestion communauté',
        category: 'customer_service',
        task_category: 'Communauté',
        roi_estimate: '3h/semaine',
        roi_detail: '2h/semaine sur les réponses + 1h sur la modération',
        use_cases: ['community', 'social', 'customer_service'],
      },
    ],
  },

  b2b: {
    slug: 'b2b',
    label: 'B2B',
    description: 'Vente B2B, SaaS enterprise, services aux entreprises — scale ta prospection.',
    icon: '',
    tasks: [
      {
        id: 'b2b-enrichissement-leads',
        label: 'Enrichissement leads',
        category: 'prospecting',
        task_category: 'Prospection',
        roi_estimate: '6h/semaine',
        roi_detail: '4h/semaine sur l\'enrichissement + 2h sur la qualification',
        use_cases: ['prospecting', 'leads', 'enrichment', 'b2b'],
      },
      {
        id: 'b2b-cold-email',
        label: 'Cold email',
        category: 'prospecting',
        task_category: 'Prospection',
        roi_estimate: '5h/semaine',
        roi_detail: '3h/semaine sur la rédaction + 2h sur la personnalisation',
        use_cases: ['email', 'outreach', 'prospecting', 'cold'],
      },
      {
        id: 'b2b-contenu-linkedin',
        label: 'Contenu LinkedIn',
        category: 'social',
        task_category: 'Marketing',
        roi_estimate: '4h/semaine',
        roi_detail: '3h/semaine sur la création de posts + 1h sur l\'engagement',
        use_cases: ['social', 'linkedin', 'content', 'b2b'],
      },
      {
        id: 'b2b-crm-automation',
        label: 'Automatisation CRM',
        category: 'automation',
        task_category: 'Opérations',
        roi_estimate: '4h/semaine',
        roi_detail: '3h/semaine sur les workflows + 1h sur la maintenance',
        use_cases: ['automation', 'crm', 'workflow'],
      },
      {
        id: 'b2b-analyse-marche',
        label: 'Analyse marché',
        category: 'research',
        task_category: 'Marketing',
        roi_estimate: '3h/semaine',
        roi_detail: '2h/semaine sur la recherche + 1h sur la synthèse',
        use_cases: ['research', 'market', 'analysis', 'b2b'],
      },
      {
        id: 'b2b-contenu-marketing',
        label: 'Création contenu marketing',
        category: 'copywriting',
        task_category: 'Marketing',
        roi_estimate: '4h/semaine',
        roi_detail: '3h/semaine sur la rédaction + 1h sur la distribution',
        use_cases: ['copywriting', 'content', 'marketing', 'b2b'],
      },
    ],
  },
}

export const SECTOR_SLUGS = Object.keys(SECTORS) as SectorSlug[]

export function getSector(slug: string): SectorConfig | null {
  return SECTORS[slug as SectorSlug] ?? null
}
